{
  flake.modules.homeManager.xdg = { config, pkgs, lib, ... }: {
    home = {
      packages = [ pkgs.xdg-utils ];
      preferXdgDirectories = true; # Makes programes use SDG directories whenever supported
    };
    # lib.optionalAttrs is a function that adds the attr set if the condition is true
    xdg = lib.optionalAttrs pkgs.stdenv.hostPlatform.isLinux {
      enable = true;

      userDirs = {
        enable = true;

        publicShare = builtins.null;
        templates = builtins.null;
      };
      # THIS FOLLOWING CONCERNS THE COMMENTED LINE
      # lib.mapAttrs applies a function to all the attributes in the atribute set.
      # The "//" are used to add the following to the attrs set on top of it.
      # https://nix.dev/manual/nix/2.28/language/operators
      # This is used if you want to use different home folders as the autogenerated ones are fine for me

      #// (lib.mapAttrs (_: folderName: "${config.home.homeDirectory}/${folderName}") {

      # ADDITIONAL NOT FOR THE COMMENTED LINE ON TOP :
      # If you wish to use it, remove the ";", uncomment the line obviously.
      # Afterwards, end the attrs with "});" because its a function.
      mimeApps = {
        enable = true;

        # The following isn't from gaetan lepage's nix-files.
        # It is my own creation and im kinda proud of it and it took quite a while
        # And really only removes unnessesary strings that are being replaced with all my comments
        # But its the chad way.
        defaultApplications = 
          let
            # Defines an attrs of programs
            applications = {
              browser = "librewolf";
              viewers = {
                pdf = "org.pwmt.zathura";
                image = "nomacs";
                video = "mpv";
              };
            };

            # Very simple function. The "_" is just notation to signify the arg is useless.
            # And I looked for it for a bit if it was official syntax for some reason
            # But yeah, no, I think its just c syntax that I stole from the line I talk about above
            mkDesktop = _: applicationName: applicationName + ".desktop";
          # This isn't even complicated but still took me a bit to figure out.
          # All you need to know is that "lib.attrsets.mapAttrsRecursive"
          # Has 2 args.
          # - A function that has 2 arg :
          #   - The path of the attr recursion.
          #   - The value of the attr.
          # - The attrs to map the first arg to.

          in with (lib.attrsets.mapAttrsRecursive mkDesktop applications); {

            # Applications
            "application/pdf" = viewers.pdf;
            
            # Text
            "text/html" = browser;
            "text/xml" = browser;
            "x-scheme-handler/http" = browser;
            "x-scheme-handler/https" = browser;
            
            # Images
            "image/gif" = viewers.image;
            "image/heif" = viewers.image;
            "image/jpeg" = viewers.image;
            "image/png" = viewers.image;
            "image/svg+xml" = viewers.image;
            "image/webp" = viewers.image;
            
            # Videos
            "video/mp4" = viewers.video; # .mp4
            "video/quicktime" = viewers.video; # .mov
            "video/x-matroska" = viewers.video; # .mkv
            "video/x-ms-wmv" = viewers.video; # .wmv
          };
      };
    };
  };
}
